Implement colored filenames based on file status
weirongxu/coc-explorer pull request #299
Opened 2020-10-30 19:58 UTC by MonliH

This PR implements coloured filenames based on git and diagnostic status, as requested in #293. This is what it looks like (with a custom colour scheme):
![image](https://user-images.githubusercontent.com/30177086/97750526-d8fb1300-1ae8-11eb-9db7-0d8ac4f9dc3c.png)

I also ran `npx prettier -w  .`, and it formatted a few other files, to my suprise. The filename for `src/git/manager.test.ts` was originally `src/git/manater.test.ts`, which I renamed.

I will document the new highlights added after this gets merged.

2020-11-01 14:32 UTC, weirongxu requested changes

2020-11-01 14:32 UTC, weirongxu commented on src/diagnosticManager.ts
> +          const warningPathsNew: Set<string> = new Set();
These variables are never used?

2020-11-01 14:32 UTC, weirongxu commented on src/diagnosticManager.ts
> +    });
Why not call `getMixedError` and `getMixedWarning` directly, are they different?

2020-11-02 03:19 UTC, merged

2020-11-02 03:19 UTC, weirongxu commented
Thank you very much! :tada:

2020-11-02 12:02 UTC, MonliH commented
No problem, I'm looking to contribute again here, `coc-explorer` is an awesome project!